
CREATE TABLE Users(UserID INT NOT NULL AUTO_INCREMENT, Name VARCHAR(50) NOT NULL, Age INT, Gender CHAR, Email VARCHAR(300) NOT NULL, PRIMARY KEY(UserID));
CREATE TABLE Posts(PostID INT NOT NULL AUTO_INCREMENT, UserID INT NOT NULL, Title VARCHAR(50) NOT NULL, Description VARCHAR(1000) NOT NULL, Image VARCHAR(300), PRIMARY KEY(PostID), FOREIGN KEY(UserID) REFERENCES Users(UserID));
CREATE TABLE Likes(LikeID INT NOT NULL AUTO_INCREMENT, UserID INT NOT NULL, PostID INT NOT NULL, PRIMARY KEY(LikeID), FOREIGN KEY(UserID) REFERENCES Users(UserID), FOREIGN KEY(PostID) REFERENCES Posts(PostID));
CREATE TABLE Comments(CommentID INT NOT NULL AUTO_INCREMENT, UserID INT NOT NULL, PostID INT NOT NULL, TextField VARCHAR(1000) NOT NULL, PRIMARY KEY(CommentID), FOREIGN KEY(UserID) REFERENCES Users(UserID), FOREIGN KEY(PostID) REFERENCES Posts(PostID));

show tables;
desc likes;
desc users;
DROP TABLE posts;
DROP TABLE likes;
DROP TABLE comments;
DROP TABLE users;